WIP Localizations
fission-codes/fission-codes pull request #14
Opened 2018-09-29 23:12 UTC by jenncoop

**Summary**

Improvements to localizations

This PR fixes/implements the following **bugs/features**

* [ ] Updates truffle to 5.0.0-beta.00
* [ ] Adds .cache to .gitignore
* [ ] Incorporates the `ethereum-localized-messaging` npm lib 
* [ ] Fixes broken specs
* [ ] Moves specific localization contracts into `fission-translations` repo

Explain the **motivation** for making this change. What existing problem does the pull request solve?

Abstracts generalized localization logic into lib.

**Test plan (required)**

WIP

**Code formatting**

WIP

2018-09-29 23:16 UTC, expede commented
> Code formatting
> WIP

@jenncoop friendly FYI: Solidity convention is 4 spaces for indentation. It also may make it easier to look at diffs

2018-10-03 15:56 UTC, expede commented on contracts/localization/FissionLocalization.sol
> +import "/ethereum-localized-messaging/contracts/Localization.sol";
👍

2018-10-03 21:14 UTC, expede commented on package.json
> +    "1066"
I guess this should also list `erc-1444` in here now, too

2018-10-03 21:15 UTC, expede requested changes

2018-10-03 21:15 UTC, expede commented on package.json
> +    "1066"
Actually, maybe `erc` `1066` should become `erc-1066` as well

2018-10-03 21:15 UTC, expede commented on contracts/Status.sol
> +    AppReason,
@jenncoop this entire file

2018-10-03 21:16 UTC, expede commented on contracts/localization/StatusCodeLocalization.sol
> -}
👍

2018-10-03 21:17 UTC, jenncoop commented on contracts/Status.sol
> +    AppReason,
will fix 👍

2018-10-03 21:17 UTC, expede commented on contracts/Status.sol
> +  }
👍

2018-10-03 21:26 UTC, expede commented on contracts/Status.sol
>      }
Can we make this overloaded?

```solidity
function requireOk(byte _status, string message) public pure {
    require(isOk(_status), message);
}

function requireOk(byte _status, LocalizationPreferences _prefs) public view {
    (bool _, string message) = localizeBy(_status, _prefs);
    requireOk(_status, message);
}
```

2018-10-03 21:26 UTC, expede commented on contracts/Status.sol
> +        require(found);
Needs to actually check if `isOk`. The overlaoded comment below includes the expected behaviour

2018-10-03 21:27 UTC, expede commented on contracts/Status.sol
> +        require(found);
Optional: if you could add a `_` rather than just omitting it. Makes it easier to read IMO.

2018-10-03 21:28 UTC, expede requested changes
Getting really close! Just a handful of small comments.

2018-10-03 21:39 UTC, jenncoop commented on contracts/Status.sol
> +        require(found);
I believe the `_` doesn't compile - I agree it's nicer

2018-10-03 21:39 UTC, expede commented on contracts/Status.sol
>      }
Oops. Updated

2018-10-03 21:44 UTC, expede commented on contracts/Status.sol
> +        require(found);
It does compile, but you need to include the type

2018-10-03 21:44 UTC, expede commented on contracts/Status.sol
> +        require(found);
ie: `(bool _, string message)`

2018-10-03 21:45 UTC, expede commented on contracts/Status.sol
> +        require(found);
_because Solidity_ 🤷‍♀️

2018-10-03 22:01 UTC, expede approved these changes
![](https://res.cloudinary.com/teepublic/image/private/s--vjQU3seL--/t_Preview/b_rgb:0195c3,c_limit,f_jpg,h_630,q_90,w_630/v1446191396/production/designs/132063_0.jpg)
![high highest of fives explosion](https://user-images.githubusercontent.com/1052016/46442000-1da2fd00-c71d-11e8-968c-eb278706a9aa.gif)
![](https://i.kym-cdn.com/photos/images/newsfeed/000/242/631/382.gif)
![](https://i.imgur.com/Q0V3Eq2.jpg)

2018-10-04 16:00 UTC, merged